version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "[deps][gha] "
  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "[deps][dotnet] "
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "[deps][ext] "
    cooldown:
      default-days: 30
      include:
        - "*json*"
